ARG NIFI_VERSION=1.11.4
ARG PORT=8080


FROM apache/nifi:$NIFI_VERSION
# COPY /custom-proc/nifi-mycustomproc-nar/target/*.nar /opt/nifi/nifi-NIFI_VERSION/lib/
# COPY /custom-proc/nifi-mycustomproc-nar/pom.xml /custom-proc/nifi-mycustomproc-nar/target/*.nar /opt/nifi/nifi-$NIFI_VERSION/lib/
EXPOSE $PORT