version: '3.7'

networks:
    nifi_network:
        driver: bridge

services:
  correto-11-jdk:
    image: correto-jdk
    container_name: java-dev
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /opt/working
    volumes:
      - .:/opt/working
    command: tail -F anything

  nifi:
    build:
      context: ./nifi
      dockerfile: Dockerfile
    volumes:
      - ./nifi/nifi-local-data/conf:/opt/nifi/nifi-current/conf
    networks:
      - nifi_network
    ports:
      - 8080:8080