version: "3.7"

networks:
    nifi_network:
        driver: bridge

services:
    nifi:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./nifi/nifi-local-data/conf:/opt/nifi/nifi-current/conf
        networks:
            - nifi_network
        ports:
            - 8080:8080
